//
//  LoginRouter.swift
//  Bank
//
//  Created by Oscar Veroneze Junior on 12/04/19.
//  Copyright (c) 2019 Junior Veroneze. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
//    func routeToCurrency(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationViewController = segue.destination as! ExtractViewController
//            let destinationDataStore = destinationViewController.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDataStore)
//        }
//
//        func passDataToSomewhere(source: LoginDataStore, destination: inout ExtractViewController) {
//            destination.userAccount = source.userAccount
//        }
//    }
}
