//
//  LoginPresenter.swift
//  Bank
//
//  Created by Oscar Veroneze Junior on 12/04/19.
//  Copyright (c) 2019 Junior Veroneze. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func showErrorMessage(message: String, errorView: UIView, errorLabel: UILabel)
    func showErrorTextField(textField: UITextField)
    func removeErrorTextField(textField: UITextField)
    func removeErrorMessage(errorView: UIView)
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    func showErrorMessage(message: String, errorView: UIView, errorLabel: UILabel) {
        errorView.isHidden = false
        errorLabel.text = message
    }
    
    func showErrorTextField(textField: UITextField) {
        textField.layer.cornerRadius = 4
        textField.layer.borderWidth = 1
        textField.layer.borderColor = #colorLiteral(red: 0.9411764706, green: 0, blue: 0, alpha: 1)
    }
    
    func removeErrorTextField(textField: UITextField) {
        textField.layer.borderWidth = 0
    }
    
    func removeErrorMessage(errorView: UIView) {
        errorView.isHidden = true
    }
}
