//
//  ExtractInteractor.swift
//  Bank
//
//  Created by Oscar Veroneze Junior on 12/04/19.
//  Copyright (c) 2019 Junior Veroneze. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExtractBusinessLogic
{
  func doSomething(request: Extract.Something.Request)
}

protocol ExtractDataStore
{
  //var name: String { get set }
}

class ExtractInteractor: ExtractBusinessLogic, ExtractDataStore
{
  var presenter: ExtractPresentationLogic?
  var worker: ExtractWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Extract.Something.Request)
  {
    worker = ExtractWorker()
    worker?.doSomeWork()
    
    let response = Extract.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
